<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PhigrosCli</RootNamespace>
    <AssemblyName>PhigrosCli</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/PhigrosLibrary/PhigrosLibrary.csproj" />
  </ItemGroup>

</Project>
